### ISSUE TITLE
and you know that's strange... but your class AddRemoveCartTest doesn't have ".java" and your code doesn't want to compilate in my Intelijy because of that. I can read your code only in github. It's better to fix that ASAP

### ISSUE THREAD

**Issue by shibiza** [shibiza/group_3#8]
and you know that's strange... but your class AddRemoveCartTest doesn't have ".java" and your code doesn't want to compilate in my Intelijy because of that. I can read your code only in github. It's better to fix that ASAP

_Originally posted by @shibiza in https://github.com/shibiza/group_3/issues/1#issuecomment-1222390465_

**Comment by Petr-Kv** [comment]
added ".java" to the filename.
